version: "3.7"
services:
  mutants_mongodb:
    container_name: mutants_mongodb
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/configdb:/data/configdb
    ports:
      - "27017:27017"
  mutants_api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    container_name: mutants_api
    links:
      - mutants_mongodb