version: "3.8"
services:
  mutants-api:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8091:8091
    volumes:
      - ./config:/app/config
    container_name: mutants-api
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017